version: '3.8'

services:
  eyesense-backend:
    build: .
    ports:
      - "8090:8090"
    environment:
      # Application configuration
      SPRING_PROFILES_ACTIVE: "docker"
      
      # Database configuration (H2 in-memory)
      SPRING_DATASOURCE_URL: "jdbc:h2:mem:testdb"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.h2.Driver"
      SPRING_DATASOURCE_USERNAME: "sa"
      SPRING_DATASOURCE_PASSWORD: ""
      
      # AWS Configuration (override with your values)
      AWS_REGION: "us-east-1"
      AWS_S3_BUCKET: "eyesense-demo-ml-api"
      AWS_S3_PUBLICBASEURL: "https://%s.s3.amazonaws.com"
      
      # AWS Credentials (set these in your environment or .env file)
      # AWS_ACCESS_KEY_ID: "your-access-key"
      # AWS_SECRET_ACCESS_KEY: "your-secret-key"
      # AWS_SESSION_TOKEN: "your-session-token"  # if using temporary credentials
      
      # AI API Configuration
      AI_API_BASE_URL: "http://localhost:8000"
    
    # Uncomment if you want to use external AWS credentials
    # env_file:
    #   - .env
    
    # Mount volume for development (optional)
    # volumes:
    #   - ./logs:/app/logs
    
    # Health check
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8090/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Restart policy
    restart: unless-stopped
    
    # Memory limits
    deploy:
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 256M

# Uncomment to add external networks
# networks:
#   default:
#     external: true
#     name: eyesense-network