spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    username: ${POSTGRES_USER}
    password: ${EYE_SENSE_ADMIN_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  thymeleaf:
    cache: false
server:
  port: ${SERVER_PORT}

aws:
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}
    publicBaseUrl: ${AWS_S3_PUBLIC_BASE_URL}

ai:
  api:
    base-url: ${AI_API_BASE_URL}
